apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: myapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80

