apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    name: enam
    app: myapp
spec:
  containers:
    - name: cont1
      image: ubuntu:latest
      command:
        - /bin/bash
        - -c
        - |
          while true;
          do 
           echo -e "Hi node selector\nthis is running on node having label as env";
           sleep 5;
          done
  nodeSelector:
    env: prod
