apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: enam
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: "500m"
      defaultRequest:
        memory: 0.5Gi
        cpu: "400m"
      type: Container

