apiVersion: v1
kind: Pod
metadata:
  name: emptyvol-pod
  labels:
    app: myvol
spec:
  containers:
    - name: cont1
      image: ubuntu:latest
      command: [ "/bin/bash", "-c", "sleep 18000" ]
      volumeMounts:
        - name: voldir
          mountPath: "tmp/data"
  volumes:
    - name: voldir
      emptyDir: {}

