apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    topic: networking
    subtopic: pod-pod-comm
spec:
  containers:
    - name: cont1
      image: httpd
      ports:
        - containerPort: 80

