apiVersion: v1
kind: Pod
metadata:
  name: cont-to-cont-comm-inside-same-pod
  labels:
    topic: networking
    subtopic: cont-cont
spec:
  containers:
    - name: cont1
      image: ubuntu
      command:
        - /bin/bash
        - -c
        - |
          while true;
          do 
           echo "Hi Bhupi Sir";
           sleep 5;
          done
    - name: cont2
      image: httpd
      ports:
        - containerPort: 80

