apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    version: "0.1"
spec:
  containers:
    - name: cont1
      image: ubuntu:latest
      command:
        - /bin/bash
        - -c
        - |
          while true; do
            echo "Hi from Secret! Secret is accessible from inside conatiner1";
            sleep 10;
          done
      volumeMounts:
        - name: mysecret-vol
          mountPath: /tmp/mysecret
  volumes:
   - name: mysecret-vol
     secret:
       secretName: mysecret


