apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    test: liveness
spec:
  containers:
    - name: cont1
      image: ubuntu:latest
      args:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 1000
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 30

