apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    version: "0.1"
spec:
  containers:
    - name: cont1
      image: ubuntu
      command:
        - /bin/bash
        - -c
        - |
          while true;
          do
           echo "Hi Configmap and Secrets";
           sleep 5;
          done
      env:
      - name: democonf
        valueFrom:
          configMapKeyRef:
            name: myconf
            key: xyz.conf

